from django import forms
from .models import User

class UserForm(forms.ModelForm):
    # Dropdown choices
    Your_COUNTRY_CHOICES = [
        ('', 'Select Which Country Belong to '),
        ('AFG', 'Afghanistan'),
('ALB', 'Albania'),
('DZA', 'Algeria'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('ATG', 'Antigua and Barbuda'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaijan'),
('BHS', 'Bahamas'),
('BHR', 'Bahrain'),
('BGD', 'Bangladesh'),
('BRB', 'Barbados'),
('BLR', 'Belarus'),
('BEL', 'Belgium'),
('BLZ', 'Belize'),
('BEN', 'Benin'),
('BTN', 'Bhutan'),
('BOL', 'Bolivia'),
('BIH', 'Bosnia and Herzegovina'),
('BWA', 'Botswana'),
('BRA', 'Brazil'),
('BRN', 'Brunei'),
('BGR', 'Bulgaria'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('CPV', 'Cabo Verde'),
('KHM', 'Cambodia'),
('CMR', 'Cameroon'),
('CAN', 'Canada'),
('CAF', 'Central African Republic'),
('TCD', 'Chad'),
('CHL', 'Chile'),
('CHN', 'China'),
('COL', 'Colombia'),
('COM', 'Comoros'),
('COG', 'Congo'),
('CRI', 'Costa Rica'),
('HRV', 'Croatia'),
('CUB', 'Cuba'),
('CYP', 'Cyprus'),
('CZE', 'Czech Republic'),
('DNK', 'Denmark'),
('DJI', 'Djibouti'),
('DMA', 'Dominica'),
('DOM', 'Dominican Republic'),
('ECU', 'Ecuador'),
('EGY', 'Egypt'),
('SLV', 'El Salvador'),
('GNQ', 'Equatorial Guinea'),
('ERI', 'Eritrea'),
('EST', 'Estonia'),
('SWZ', 'Eswatini'),
('ETH', 'Ethiopia'),
('FJI', 'Fiji'),
('FIN', 'Finland'),
('FRA', 'France'),
('GAB', 'Gabon'),
('GMB', 'Gambia'),
('GEO', 'Georgia'),
('DEU', 'Germany'),
('GHA', 'Ghana'),
('GRC', 'Greece'),
('GRD', 'Grenada'),
('GTM', 'Guatemala'),
('GIN', 'Guinea'),
('GNB', 'Guinea-Bissau'),
('GUY', 'Guyana'),
('HTI', 'Haiti'),
('HND', 'Honduras'),
('HUN', 'Hungary'),
('ISL', 'Iceland'),
('IND', 'India'),
('IDN', 'Indonesia'),
('IRN', 'Iran'),
('IRQ', 'Iraq'),
('IRL', 'Ireland'),
('ISR', 'Israel'),
('ITA', 'Italy'),
('JAM', 'Jamaica'),
('JPN', 'Japan'),
('JOR', 'Jordan'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KIR', 'Kiribati'),
('PRK', 'North Korea'),
('KOR', 'South Korea'),
('KWT', 'Kuwait'),
('KGZ', 'Kyrgyzstan'),
('LAO', 'Laos'),
('LVA', 'Latvia'),
('LBN', 'Lebanon'),
('LSO', 'Lesotho'),
('LBR', 'Liberia'),
('LBY', 'Libya'),
('LIE', 'Liechtenstein'),
('LTU', 'Lithuania'),
('LUX', 'Luxembourg'),
('MDG', 'Madagascar'),
('MWI', 'Malawi'),
('MYS', 'Malaysia'),
('MDV', 'Maldives'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MHL', 'Marshall Islands'),
('MRT', 'Mauritania'),
('MUS', 'Mauritius'),
('MEX', 'Mexico'),
('FSM', 'Micronesia'),
('MDA', 'Moldova'),
('MCO', 'Monaco'),
('MNG', 'Mongolia'),
('MNE', 'Montenegro'),
('MAR', 'Morocco'),
('MOZ', 'Mozambique'),
('MMR', 'Myanmar'),
('NAM', 'Namibia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NLD', 'Netherlands'),
('NZL', 'New Zealand'),
('NIC', 'Nicaragua'),
('NER', 'Niger'),
('NGA', 'Nigeria'),
('MKD', 'North Macedonia'),
('NOR', 'Norway'),
('OMN', 'Oman'),
('PAK', 'Pakistan'),
('PLW', 'Palau'),
('PAN', 'Panama'),
('PNG', 'Papua New Guinea'),
('PRY', 'Paraguay'),
('PER', 'Peru'),
('PHL', 'Philippines'),
('POL', 'Poland'),
('PRT', 'Portugal'),
('QAT', 'Qatar'),
('ROU', 'Romania'),
('RUS', 'Russia'),
('RWA', 'Rwanda'),
('KNA', 'Saint Kitts and Nevis'),
('LCA', 'Saint Lucia'),
('VCT', 'Saint Vincent and the Grenadines'),
('WSM', 'Samoa'),
('SMR', 'San Marino'),
('STP', 'Sao Tome and Principe'),
('SAU', 'Saudi Arabia'),
('SEN', 'Senegal'),
('SRB', 'Serbia'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leone'),
('SGP', 'Singapore'),
('SVK', 'Slovakia'),
('SVN', 'Slovenia'),
('SLB', 'Solomon Islands'),
('SOM', 'Somalia'),
('ZAF', 'South Africa'),
('ESP', 'Spain'),
('LKA', 'Sri Lanka'),
('SDN', 'Sudan'),
('SUR', 'Suriname'),
('SWE', 'Sweden'),
('CHE', 'Switzerland'),
('SYR', 'Syria'),
('TJK', 'Tajikistan'),
('TZA', 'Tanzania'),
('THA', 'Thailand'),
('TLS', 'Timor-Leste'),
('TGO', 'Togo'),
('TON', 'Tonga'),
('TTO', 'Trinidad and Tobago'),
('TUN', 'Tunisia'),
('TUR', 'Turkey'),
('TKM', 'Turkmenistan'),
('TUV', 'Tuvalu'),
('UGA', 'Uganda'),
('UKR', 'Ukraine'),
('ARE', 'United Arab Emirates'),
('GBR', 'United Kingdom'),
('USA', 'United States'),
('URY', 'Uruguay'),
('UZB', 'Uzbekistan'),
('VUT', 'Vanuatu'),
('VEN', 'Venezuela'),
('VNM', 'Vietnam'),
('YEM', 'Yemen'),
('ZMB', 'Zambia'),
('ZWE', 'Zimbabwe')
    ]
    COUNTRY_CHOICES = [
        ('', 'Select Preferred Country For Study'),
        ('USA', 'United States'),
        ('Canada', 'Canada'),
        ('UK', 'United Kingdom'),
        ('Australia', 'Australia'),
        ('Italy','Italy'),
        ('AFG', 'Afghanistan'),
('ALB', 'Albania'),
('DZA', 'Algeria'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('ATG', 'Antigua and Barbuda'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaijan'),
('BHS', 'Bahamas'),
('BHR', 'Bahrain'),
('BGD', 'Bangladesh'),
('BRB', 'Barbados'),
('BLR', 'Belarus'),
('BEL', 'Belgium'),
('BLZ', 'Belize'),
('BEN', 'Benin'),
('BTN', 'Bhutan'),
('BOL', 'Bolivia'),
('BIH', 'Bosnia and Herzegovina'),
('BWA', 'Botswana'),
('BRA', 'Brazil'),
('BRN', 'Brunei'),
('BGR', 'Bulgaria'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('CPV', 'Cabo Verde'),
('KHM', 'Cambodia'),
('CMR', 'Cameroon'),
('CAN', 'Canada'),
('CAF', 'Central African Republic'),
('TCD', 'Chad'),
('CHL', 'Chile'),
('CHN', 'China'),
('COL', 'Colombia'),
('COM', 'Comoros'),
('COG', 'Congo'),
('CRI', 'Costa Rica'),
('HRV', 'Croatia'),
('CUB', 'Cuba'),
('CYP', 'Cyprus'),
('CZE', 'Czech Republic'),
('DNK', 'Denmark'),
('DJI', 'Djibouti'),
('DMA', 'Dominica'),
('DOM', 'Dominican Republic'),
('ECU', 'Ecuador'),
('EGY', 'Egypt'),
('SLV', 'El Salvador'),
('GNQ', 'Equatorial Guinea'),
('ERI', 'Eritrea'),
('EST', 'Estonia'),
('SWZ', 'Eswatini'),
('ETH', 'Ethiopia'),
('FJI', 'Fiji'),
('FIN', 'Finland'),
('FRA', 'France'),
('GAB', 'Gabon'),
('GMB', 'Gambia'),
('GEO', 'Georgia'),
('DEU', 'Germany'),
('GHA', 'Ghana'),
('GRC', 'Greece'),
('GRD', 'Grenada'),
('GTM', 'Guatemala'),
('GIN', 'Guinea'),
('GNB', 'Guinea-Bissau'),
('GUY', 'Guyana'),
('HTI', 'Haiti'),
('HND', 'Honduras'),
('HUN', 'Hungary'),
('ISL', 'Iceland'),
('IND', 'India'),
('IDN', 'Indonesia'),
('IRN', 'Iran'),
('IRQ', 'Iraq'),
('IRL', 'Ireland'),
('ISR', 'Israel'),
('ITA', 'Italy'),
('JAM', 'Jamaica'),
('JPN', 'Japan'),
('JOR', 'Jordan'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KIR', 'Kiribati'),
('PRK', 'North Korea'),
('KOR', 'South Korea'),
('KWT', 'Kuwait'),
('KGZ', 'Kyrgyzstan'),
('LAO', 'Laos'),
('LVA', 'Latvia'),
('LBN', 'Lebanon'),
('LSO', 'Lesotho'),
('LBR', 'Liberia'),
('LBY', 'Libya'),
('LIE', 'Liechtenstein'),
('LTU', 'Lithuania'),
('LUX', 'Luxembourg'),
('MDG', 'Madagascar'),
('MWI', 'Malawi'),
('MYS', 'Malaysia'),
('MDV', 'Maldives'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MHL', 'Marshall Islands'),
('MRT', 'Mauritania'),
('MUS', 'Mauritius'),
('MEX', 'Mexico'),
('FSM', 'Micronesia'),
('MDA', 'Moldova'),
('MCO', 'Monaco'),
('MNG', 'Mongolia'),
('MNE', 'Montenegro'),
('MAR', 'Morocco'),
('MOZ', 'Mozambique'),
('MMR', 'Myanmar'),
('NAM', 'Namibia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NLD', 'Netherlands'),
('NZL', 'New Zealand'),
('NIC', 'Nicaragua'),
('NER', 'Niger'),
('NGA', 'Nigeria'),
('MKD', 'North Macedonia'),
('NOR', 'Norway'),
('OMN', 'Oman'),
('PAK', 'Pakistan'),
('PLW', 'Palau'),
('PAN', 'Panama'),
('PNG', 'Papua New Guinea'),
('PRY', 'Paraguay'),
('PER', 'Peru'),
('PHL', 'Philippines'),
('POL', 'Poland'),
('PRT', 'Portugal'),
('QAT', 'Qatar'),
('ROU', 'Romania'),
('RUS', 'Russia'),
('RWA', 'Rwanda'),
('KNA', 'Saint Kitts and Nevis'),
('LCA', 'Saint Lucia'),
('VCT', 'Saint Vincent and the Grenadines'),
('WSM', 'Samoa'),
('SMR', 'San Marino'),
('STP', 'Sao Tome and Principe'),
('SAU', 'Saudi Arabia'),
('SEN', 'Senegal'),
('SRB', 'Serbia'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leone'),
('SGP', 'Singapore'),
('SVK', 'Slovakia'),
('SVN', 'Slovenia'),
('SLB', 'Solomon Islands'),
('SOM', 'Somalia'),
('ZAF', 'South Africa'),
('ESP', 'Spain'),
('LKA', 'Sri Lanka'),
('SDN', 'Sudan'),
('SUR', 'Suriname'),
('SWE', 'Sweden'),
('CHE', 'Switzerland'),
('SYR', 'Syria'),
('TJK', 'Tajikistan'),
('TZA', 'Tanzania'),
('THA', 'Thailand'),
('TLS', 'Timor-Leste'),
('TGO', 'Togo'),
('TON', 'Tonga'),
('TTO', 'Trinidad and Tobago'),
('TUN', 'Tunisia'),
('TUR', 'Turkey'),
('TKM', 'Turkmenistan'),
('TUV', 'Tuvalu'),
('UGA', 'Uganda'),
('UKR', 'Ukraine'),
('ARE', 'United Arab Emirates'),
('GBR', 'United Kingdom'),
('USA', 'United States'),
('URY', 'Uruguay'),
('UZB', 'Uzbekistan'),
('VUT', 'Vanuatu'),
('VEN', 'Venezuela'),
('VNM', 'Vietnam'),
('YEM', 'Yemen'),
('ZMB', 'Zambia'),
('ZWE', 'Zimbabwe')
    ]

    DEGREE_CHOICES = [
        ('', 'Select Degree'),
        ('Bachelors', 'Bachelors'),
        ('Masters', 'Masters'),
    ]

    BOARD_CHOICES = [
        ('', 'Select Preferred Course For Study'),
        ('CSE', 'Computer Science and Engineering'),
('ME', 'Mechanical Engineering'),
('CE', 'Civil Engineering'),
('EEE', 'Electrical and Electronics Engineering'),
('ECE', 'Electronics and Communication Engineering'),
('Aero', 'Aerospace Engineering'),
('Chem', 'Chemical Engineering'),
('Biotech', 'Biotechnology Engineering'),
('Arch', 'Architecture'),
('IT', 'Information Technology'),
('AI', 'Artificial Intelligence'),
('ML', 'Machine Learning'),
('DS', 'Data Science'),
('CS', 'Cyber Security'),
('Auto', 'Automobile Engineering'),
('Mechatronics', 'Mechatronics Engineering'),
('Petro', 'Petroleum Engineering'),
('Mining', 'Mining Engineering'),
('Agri', 'Agricultural Engineering'),
('Env', 'Environmental Engineering'),
('IE', 'Industrial Engineering'),
('Marine', 'Marine Engineering'),
('Textile', 'Textile Engineering'),
('Nano', 'Nanotechnology'),
('Robotics', 'Robotics Engineering'),
('Pharma', 'Pharmaceutical Engineering'),
('Metallurgy', 'Metallurgical Engineering'),
('Geo', 'Geotechnical Engineering'),
('Renewable', 'Renewable Energy Engineering'),
('Nuclear', 'Nuclear Engineering'),
('MBBS', 'Bachelor of Medicine and Bachelor of Surgery'),
('BDS', 'Bachelor of Dental Surgery'),
('BScN', 'Bachelor of Science in Nursing'),
('BPharm', 'Bachelor of Pharmacy'),
('BPT', 'Bachelor of Physiotherapy'),
('BMLT', 'Bachelor of Medical Laboratory Technology'),
('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery'),
('BHMS', 'Bachelor of Homeopathic Medicine and Surgery'),
('BUMS', 'Bachelor of Unani Medicine and Surgery'),
('BVSc', 'Bachelor of Veterinary Science'),
('BAEng', 'Bachelor of Arts in English'),
('BAHis', 'Bachelor of Arts in History'),
('BAPsy', 'Bachelor of Arts in Psychology'),
('BASoc', 'Bachelor of Arts in Sociology'),
('BAEco', 'Bachelor of Arts in Economics'),
('BAPol', 'Bachelor of Arts in Political Science'),
('BAPhil', 'Bachelor of Arts in Philosophy'),
('BAJour', 'Bachelor of Arts in Journalism'),
('BALit', 'Bachelor of Arts in Literature'),
('BALang', 'Bachelor of Arts in Languages'),
('BScPhy', 'Bachelor of Science in Physics'),
('BScChem', 'Bachelor of Science in Chemistry'),
('BScMath', 'Bachelor of Science in Mathematics'),
('BScBio', 'Bachelor of Science in Biology'),
('BScCS', 'Bachelor of Science in Computer Science'),
('BScEnv', 'Bachelor of Science in Environmental Science'),
('BScStat', 'Bachelor of Science in Statistics'),
('BScMicro', 'Bachelor of Science in Microbiology'),
('BScBiotech', 'Bachelor of Science in Biotechnology'),
('BScGeology', 'Bachelor of Science in Geology'),
('BCom', 'Bachelor of Commerce'),
('BBA', 'Bachelor of Business Administration'),
('CA', 'Chartered Accountancy'),
('CMA', 'Cost and Management Accounting'),
('CFA', 'Chartered Financial Analyst'),
('BComAcc', 'Bachelor of Commerce in Accounting'),
('BComFin', 'Bachelor of Commerce in Finance'),
('BComTax', 'Bachelor of Commerce in Taxation'),
('BComMkt', 'Bachelor of Commerce in Marketing'),
('BComIB', 'Bachelor of Commerce in International Business'),
('LLB', 'Bachelor of Laws'),
('BA LLB', 'Bachelor of Arts and Bachelor of Laws'),
('BBA LLB', 'Bachelor of Business Administration and Bachelor of Laws'),
('LLM', 'Master of Laws'),
('Criminology', 'Criminology and Criminal Justice'),
('Corporate Law', 'Corporate Law'),
('IntlLaw', 'International Law'),
('HumanRights', 'Human Rights Law'),
('IPLaw', 'Intellectual Property Law'),
('EnvLaw', 'Environmental Law'),
('BArch', 'Bachelor of Architecture'),
('BDes', 'Bachelor of Design'),
('FashionDes', 'Fashion Design'),
('IntDes', 'Interior Design'),
('GraphicDes', 'Graphic Design'),
('Anim', 'Animation and Multimedia'),
('ProdDes', 'Product Design'),
('GameDes', 'Game Design'),
('UrbanDes', 'Urban Design'),
('LandArch', 'Landscape Architecture'),
('MBA', 'Master of Business Administration'),
('MSM', 'Master of Science in Management'),
('MFin', 'Master of Finance'),
('MAcc', 'Master of Accounting'),
('MMkt', 'Master of Marketing'),
('MHRM', 'Master of Human Resource Management'),
('MSCM', 'Master of Supply Chain Management'),
('MIB', 'Master of International Business'),
('MPM', 'Master of Project Management'),

('MSE', 'Master of Science in Engineering'),
('MEng', 'Master of Engineering'),
('MSCS', 'Master of Science in Computer Science'),
('MSIT', 'Master of Science in Information Technology'),
('MSDS', 'Master of Science in Data Science'),
('MSAI', 'Master of Science in Artificial Intelligence'),
('MSCS', 'Master of Science in Cybersecurity'),
('MSEE', 'Master of Science in Electrical Engineering'),
('MSME', 'Master of Science in Mechanical Engineering'),
('MSCE', 'Master of Science in Civil Engineering'),
('MSAE', 'Master of Science in Aerospace Engineering'),
('MSBME', 'Master of Science in Biomedical Engineering'),

('MSP', 'Master of Science in Physics'),
('MSC', 'Master of Science in Chemistry'),
('MSB', 'Master of Science in Biology'),
('MSM', 'Master of Science in Mathematics'),
('MSES', 'Master of Science in Environmental Science'),
('MSBT', 'Master of Science in Biotechnology'),
('MSG', 'Master of Science in Geology'),
('MSA', 'Master of Science in Astronomy'),

('MAP', 'Master of Arts in Psychology'),
('MAS', 'Master of Arts in Sociology'),
('MAPS', 'Master of Arts in Political Science'),
('MAH', 'Master of Arts in History'),
('MAE', 'Master of Arts in Economics'),
('MAA', 'Master of Arts in Anthropology'),
('MAPh', 'Master of Arts in Philosophy'),
('MAIR', 'Master of Arts in International Relations'),
('MAC', 'Master of Arts in Communication'),
('MAL', 'Master of Arts in Linguistics'),

('MEd', 'Master of Education'),
('MAT', 'Master of Arts in Teaching'),
('MSEd', 'Master of Science in Education'),
('MACI', 'Master of Arts in Curriculum and Instruction'),
('MAEL', 'Master of Arts in Educational Leadership'),
('MASE', 'Master of Arts in Special Education'),

('MSN', 'Master of Science in Nursing'),
('MPH', 'Master of Public Health'),
('MSPH', 'Master of Science in Public Health'),
('MHA', 'Master of Health Administration'),
('MSCR', 'Master of Science in Clinical Research'),
('MSN', 'Master of Science in Nutrition'),
('MSP', 'Master of Science in Pharmacy'),
('MSOT', 'Master of Science in Occupational Therapy'),
('MSPT', 'Master of Science in Physical Therapy'),

('MFA', 'Master of Fine Arts'),
('MAGD', 'Master of Arts in Graphic Design'),
('MAFD', 'Master of Arts in Fashion Design'),
('MAID', 'Master of Arts in Interior Design'),
('MAFS', 'Master of Arts in Film Studies'),
('MAM', 'Master of Arts in Music'),
('MAT', 'Master of Arts in Theater'),

('LLM', 'Master of Laws'),
('MLS', 'Master of Legal Studies'),
('MDR', 'Master of Dispute Resolution'),
('MIL', 'Master of International Law'),

('MLIS', 'Master of Library and Information Science'),
('MSIS', 'Master of Science in Information Systems'),
('MSDA', 'Master of Science in Data Analytics'),

('MSEM', 'Master of Science in Environmental Management'),
('MSS', 'Master of Science in Sustainability'),
('MSCC', 'Master of Science in Climate Change'),
('MSRE', 'Master of Science in Renewable Energy'),

('MSA', 'Master of Science in Agriculture'),
('MSFS', 'Master of Science in Food Science'),
('MSAB', 'Master of Science in Agribusiness'),

('MArch', 'Master of Architecture'),
('MUP', 'Master of Urban Planning'),
('MLA', 'Master of Landscape Architecture'),

('MSAIR', 'Master of Science in Artificial Intelligence and Robotics'),
('MSBT', 'Master of Science in Blockchain Technology'),
('MSDM', 'Master of Science in Digital Marketing'),
('MSE', 'Master of Science in Entrepreneurship'),
('MSGH', 'Master of Science in Global Health')

 
    ]
   

    # Form fields
    Your_country = forms.ChoiceField(choices=Your_COUNTRY_CHOICES, required=True, label='Your Country')
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, required=True, label='Country')
    degree = forms.ChoiceField(choices=DEGREE_CHOICES, required=True, label='Degree')
    preferred_course = forms.ChoiceField(choices=BOARD_CHOICES, required=True, label='Preferred Course')

        
    name = forms.CharField(
        label="Full Name", 
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your full name'})
    )
    mobile = forms.CharField(
        label="Mobile No.", 
        max_length=15,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your mobile number'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email address'})
    )
    Your_country = forms.ChoiceField(
        choices=Your_COUNTRY_CHOICES,
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Select your country'})
    )
    country = forms.ChoiceField(
        choices=COUNTRY_CHOICES,
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Select the country for study'})
    )
    degree = forms.ChoiceField(
        choices=DEGREE_CHOICES,
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Select your degree'})
    )
    preferred_course = forms.ChoiceField(
        choices=BOARD_CHOICES,
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Select your preferred course'})
    )
    bachelors_course = forms.CharField(
        label=" Bachelor’s course",help_text="<span style='font-size: smaller; font-weight: normal;'>(If pursuing a Master's, fill this option; otherwise, Fill null.)</span>",
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your bachelor’s course (if applicable)'})
    )
    bachelors_percentage = forms.CharField(
        label="Bachelor’s percentage/CGPA",help_text="<span style='font-size: smaller; font-weight: normal;'>(If pursuing a Master's, fill this option; otherwise, Fill null.)</span>",
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your bachelor’s percentage (e.g., 85.5%)'}),
        
    )
    toefl_score = forms.CharField(
        label="TOEFL/IELTS Score",
        required=False,
        max_length=15,
        help_text="<span style='font-size: smaller; font-weight: normal;'>(If you took the exam, write the score otherwise, write null.)</span>",
        widget=forms.TextInput(attrs={'placeholder': 'Enter your TOEFL score'})
    )
    gre_score = forms.CharField(
        label="GRE Score",
        max_length=15,
        required=False,
        help_text="<span style='font-size: smaller; font-weight: normal;'>(If you took the exam, write the score otherwise, write null.)</span>",
        widget=forms.TextInput(attrs={'placeholder': 'Enter your GRE score'})
    )
    gpa_score = forms.CharField(
        label="GPA Score",
        max_length=15,
        required=False,
        help_text="<span style='font-size: smaller; font-weight: normal;'>(If you took the exam, write the score otherwise, write null.)</span>",
        widget=forms.TextInput(attrs={'placeholder': 'Enter your GPA (e.g., 3.75)'})
    )
    twelveth_percentage = forms.DecimalField(
        label="12th Percentage",
        max_digits=5,
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter your 12th-grade percentage'})
    )
    tenth_percentage = forms.DecimalField(
        label="10th Percentage",
        max_digits=5,
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter your 10th-grade percentage'})
    )

    class Meta:
        model = User
        fields = [
            'name', 'mobile', 'email','Your_country', 'country', 'board', 'degree',
            'bachelors_course', 'bachelors_percentage', 'toefl_score',
            'gre_score', 'gpa_score', 'twelveth_percentage', 'tenth_percentage',
            'preferred_course'
        ]
