# Generated by Django 5.1.1 on 2025-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('bachelors_course', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelors_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('toefl_score', models.CharField(max_length=10)),
                ('gre_score', models.CharField(max_length=10)),
                ('gpa_score', models.CharField(max_length=5)),
                ('twelveth_percentage', models.CharField(max_length=5)),
                ('tenth_percentage', models.CharField(max_length=5)),
                ('preferred_course', models.CharField(max_length=100)),
            ],
        ),
    ]
