# Generated by Django 5.1.1 on 2025-01-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_user_gpa_score_alter_user_gre_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bachelors_percentage',
            new_name='Duolingo_PTE',
        ),
    ]
